---
title: "QuantitativeMethodsForPoli-Sci"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load(tidyverse, broom)


# command opt Iで新たなcode chunk作成
# command shift Oで目次を開く
# 日本語を打つときはvisual Markdownを開いた方が良い

```

### 目次

#### 第1章 計量政治学とは

#### 第2章 研究テーマの選び方

#### 第3章 理論と仮説

#### 第4章 Rの使い方

#### 第5章 Rによるデータ操作

#### 第6章 記述統計とデータの可視化・視覚化

#### 第7章 統計的推定

#### 第8章 統計的仮説検定

#### 第9章 変数間の関連性

#### 第10章 回帰分析の基礎

#### 第11章 回帰分析による統計的推定

#### 第12章 [回帰分析の前提と妥当性の判断]{.ul}

#### 第13章 回帰分析の応用

#### 第14章 [交差項の使い**方**]{.ul}

#### 第15章 [ロジスティック回帰分析]{.ul} 

------------------------------------------------------------------------

### 第1章 計量政治学とは

省略

------------------------------------------------------------------------

### 第2章 研究テーマの選び方

Monroe(2000)によると、良い研究テーマは次の５つを満たす

-   明快さ

-   検証可能性

-   理論的重要性

-   実用性

-   独創性

> 実証研究では、事実をまとめることよりも、むしろ適切なリサーチクエスチョンを中心にバランスのとれた研究を設計することの方が重視される。

Barbara Geddes教授曰く、『テーマを選ぶ際の条件は二つあります。一つは、あなたの研究が専門分野において理論的に貢献するということ。もう一つはそのテーマが好きだということです。』

#### 2.2.2 規範的問題から実証的問題への変換方法

1.  参照枠組み（frame of reference）を変える

    日本は美しい国か？→日本国民は、日本を美しい国と考えているか？なら実証的に検討可能

規範的問題の背後にある前提条件に注目する

2.  消費税を減らすべきだ、という主張→３つの前提条件

```{=html}
<!-- -->
```
1.  消費税を減らせば、経済を刺激して消費が伸びる

2.  消費が伸びれば、雇用が増えて好景気になる

3.  好景気になれば、税収が増える

これらはそれぞれ独立に実証的に分析ができる

#### 2.2.3 パズルを探す 

・常識と異なる事実が発見されたときに、そこからRQにつながることがある

#### 2.2.4 研究論文の構成

1.  イントロダクション

2.  先行研究

    先行研究の紹介は完結にまとめるべき。先行文献は、その著者のRQとその答えを中心に探す。端から端まで読む必要はない。

3.  理論の提示

4.  仮説の提示

5.  対抗仮説の提示

6.  作業化

7.  証拠の提示

8.  結論

Political Science292B (Introduction to Political Inquiry: Research Design)より

------------------------------------------------------------------------

### 第3章 理論と仮説

#### 3.1.1 リサーチデザインのプロセス

1.  パズルを見つける
2.  それを説明するための複数の前提条件(assumptions, propositions)から理論を作る
3.  理論から作業仮説を引き出す
4.  作業仮説を検証するためのデータを集める
5.  データを使って作業仮説を検証し、理論の妥当性を確かめる
